task: FortifySCA@5
  inputs:
    licenseFile: 'c:\temp\fortify.license'
    runBuildTranslate: true
    applicationType: 'java'
    fortifyBuildId: '452020'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: true
    scaDebug: false
    runFortifyScan: true
    fortifyScanType: 'LocalScan'